import { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/reset.css";
import "../styles/globals.css";
import { NavBar } from "@/components/general/NavBar";
import SwitchMode from "@/components/general/SwitchMode";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="es">
      <body className={inter.className}>
        <NavBar />
        {children}
        <SwitchMode />
      </body>
    </html>
  );
}

